//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuccessPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventStudent
    {
        public int IdEventStudent { get; set; }
        public int IdStudent { get; set; }
        public int IdEvent { get; set; }
        public Nullable<int> IdMark { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Marks Marks { get; set; }
        public virtual Student Student { get; set; }
    }
}
