//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuccessPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkStudent
    {
        public int IdStudent { get; set; }
        public int IdMark { get; set; }
        public System.DateTime Date { get; set; }
        public int IdMarkStudent { get; set; }
        public Nullable<int> IdSubject { get; set; }
    
        public virtual Marks Marks { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
