//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuccessPlus.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuccessPlusEntities5 : DbContext
    {
        public SuccessPlusEntities5()
            : base("name=SuccessPlusEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assessment> Assessment { get; set; }
        public virtual DbSet<Elder> Elder { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventStudent> EventStudent { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<MarkStudent> MarkStudent { get; set; }
        public virtual DbSet<SignIn> SignIn { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Supervisor> Supervisor { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Visiting> Visiting { get; set; }
        public virtual DbSet<VisitingStudent> VisitingStudent { get; set; }
    }
}
