//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuccessPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor
    {
        public int IdSupervisor { get; set; }
        public string FisrtName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
