//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuccessPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitingStudent
    {
        public int IdVisitingStudent { get; set; }
        public int IdVisiting { get; set; }
        public int IdStudent { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Visiting Visiting { get; set; }
    }
}
